// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1_n99Ms6EbXFf99q0qWnFuQmfpcmTL3o',
    appId: '1:804576924281:web:c094cd278752748b42baa8',
    messagingSenderId: '804576924281',
    projectId: 'tailor-app-b5f53',
    authDomain: 'tailor-app-b5f53.firebaseapp.com',
    storageBucket: 'tailor-app-b5f53.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeAoP4WJnDHw7W-Uz_XohiDgdnHi9ELCk',
    appId: '1:804576924281:android:c7a4280d5ce8e47542baa8',
    messagingSenderId: '804576924281',
    projectId: 'tailor-app-b5f53',
    storageBucket: 'tailor-app-b5f53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU2RUp1B7b1YzW8lp7AlXsqPCJXEYmT_k',
    appId: '1:804576924281:ios:5dda3ef63ef2504c42baa8',
    messagingSenderId: '804576924281',
    projectId: 'tailor-app-b5f53',
    storageBucket: 'tailor-app-b5f53.firebasestorage.app',
    iosBundleId: 'com.exampl.tailorApp',
  );
}
